"""Build the target, audit its symbols, link the engine against it.

Two of the reference implementation's defects live here (see the audit in
plan/platform/01-decisions.md):

  #5  its launcher ran `find -maxdepth 3 -name '*.c'` and ar'd everything it
      found, sweeping up the student's own main.c -> duplicate `main`, link
      failure, zero tests, from a repository that compiles perfectly.
  #2  it detected missing functions with weak stubs returning -999, a sentinel
      that collides with real data: ft_atoi("-999") returns -999.

So: only a pack's own known basenames are ever compiled (`pack.sources`, or
nothing at all when a pack cannot enumerate them - see compile_known_sources),
and presence is decided by nm before anything is linked.

Everything here takes a `pack` (bro42/packs/__init__.py). Two facts the
manifest keeps separate and this module respects throughout: presence is
decided per SYMBOL (nm sees symbols, not suite ids), and skipping/reporting is
decided per SUITE (a suite is what the engine and the spec address). For
Libft the two coincide; for ft_printf fifteen suites share one symbol.
"""

import shutil
import subprocess
from pathlib import Path

from . import paths

# -Wl,--wrap rewrites every undefined reference to malloc - including the ones
# inside the student's archive - to __wrap_malloc. GNU ld only; Apple's ld64
# has no equivalent, so on a platform without it the flags are dropped and the
# injection cases report SKIP (decision A8).
WRAP_FLAGS = [
    "-Wl,--wrap=malloc", "-Wl,--wrap=free",
    "-Wl,--wrap=calloc", "-Wl,--wrap=realloc",
]


class BuildError(Exception):
    pass


def _run(cmd, cwd=None):
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True,
                          errors="replace")


def make_target(target):
    """make bonus, falling back to all, then to a bare make. Never fatal."""
    for args in (["make", "bonus"], ["make", "all"], ["make"]):
        r = _run(args, cwd=target)
        if r.returncode == 0:
            return {"ok": True, "cmd": " ".join(args), "output": r.stdout + r.stderr}
    return {"ok": False, "cmd": "make", "output": r.stdout + r.stderr}


def find_archive(target, pack):
    a = Path(target) / pack.artifact[1]
    return a if a.is_file() else None


def synth_header(pack, out_dir):
    """A stand-in header, built from the prototypes in the pack's own cases.json.

    A repository can have perfectly good sources and no header - the student
    has not written it yet, or it lives somewhere else. Refusing to test
    anything in that case is the wrong answer: the prototypes are already the
    canonical ones, so supply them and run the tests. The missing header is
    still reported as the Subject IV violation it is, by the macro suite.

    This is only ever called on behalf of a pack whose `sources` is a known
    basename set (compile_known_sources's fallback) - today that is only
    Libft, and the `t_list` shim below is Libft's own type. A future
    sources-having pack that needs a synthesized header of its own will have
    to generalise this, not extend it in place - see the Phase 2 handoff.
    """
    from . import content
    protos = [m["prototype"] for m in content.load(pack)["functions"].values()
              if m.get("prototype")]
    path = out_dir / pack.header
    guard = pack.header.upper().replace(".", "_")
    path.write_text(
        f"/* generated by bro42: this repository has no {pack.header} of its own */\n"
        f"#ifndef {guard}\n# define {guard}\n\n"
        "# include <stddef.h>\n# include <stdlib.h>\n# include <unistd.h>\n\n"
        "# ifndef T_LIST_DEFINED\n#  define T_LIST_DEFINED\n"
        "typedef struct s_list\n{\n\tvoid\t\t\t*content;\n"
        "\tstruct s_list\t*next;\n}\tt_list;\n# endif\n\n"
        + "\n".join(protos) + "\n\n#endif\n")
    return path


def compile_known_sources(target, pack, out_dir, info=None):
    """Fallback when make produced no archive. ONLY `pack.sources` basenames.

    A pack whose `sources` is None (ft_printf: the turn-in list allows
    arbitrary filenames in arbitrary subdirectories, so there is no closed
    set to compile) never reaches this function - see prepare(). Guessing at
    sources for such a pack is exactly defect #5 in the module docstring.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    includes = [f"-I{target}"]
    if not (Path(target) / pack.header).is_file():
        synth_header(pack, out_dir)
        includes.append(f"-I{out_dir}")
        if info is not None:
            info["synth_header"] = True
    objs, errors = [], []
    for src in sorted(Path(target).glob("*.c")):
        stem = src.stem
        # pack.sources already contains both the plain and the `_bonus`
        # basenames (see the libft pack manifest), so membership alone
        # decides it - no separate bonus-suffix rule needed here.
        if stem not in pack.sources:
            continue
        obj = out_dir / (stem + ".o")
        r = _run(["cc", "-c", str(src), "-o", str(obj)] + includes)
        if r.returncode == 0:
            objs.append(obj)
        else:
            errors.append(r.stderr.strip())
    if info is not None:
        info["compile_errors"] = errors
    if not objs:
        return None
    archive = out_dir / pack.artifact[1]
    if _run(["ar", "rcs", str(archive)] + [str(o) for o in objs]).returncode:
        return None
    return archive


def defined_symbols(archive):
    """The implemented set, decided before anything is linked or called."""
    r = _run(["nm", "-g", "--defined-only", str(archive)])
    syms = set()
    for line in r.stdout.splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[1] in ("T", "t"):
            syms.add(parts[2].lstrip("_"))
    return syms


def undefined_pack_symbols(archive, pack):
    """Per object, which of the PACK'S OWN symbols it calls but does not
    define - malloc, write and every other external are not candidates for
    being "not written yet", so they are filtered out here by membership in
    pack.symbols rather than by a literal 'ft_' prefix test.

    The per-object keying assumes an object's basename names the symbol it
    defines, which holds for every pack whose `sources` enumerates its own
    basenames (today, Libft). A pack that cannot (ft_printf) gets an empty
    or partial `deps` here rather than a crash - the "blocked" chain in
    prepare() below then simply finds nothing to propagate, which is a safe
    degradation: a single-symbol pack cannot block on itself anyway.
    """
    pack_symbols = set(pack.symbols)
    r = _run(["nm", "-u", str(archive)])
    deps, obj = {}, None
    for line in r.stdout.splitlines():
        line = line.strip()
        if line.endswith(".o:"):
            obj = line[:-3].replace("_bonus", "")
            continue
        parts = line.split()
        if len(parts) == 2 and parts[0] == "U" and obj:
            sym = parts[1].lstrip("_").split("@")[0].replace("_bonus", "")
            if sym in pack_symbols:
                deps.setdefault(obj, set()).add(sym)
    return deps


def write_stubs(missing_symbols, out_dir):
    """No-op stubs, so the link succeeds. They are never CALLED - their
    suites are skipped and reported MISSING - which is exactly the property
    the -999 sentinel design lacked."""
    if not missing_symbols:
        return None
    src = out_dir / "stubs.c"
    body = ["/* generated: link-only stubs for symbols not yet written */"]
    for sym in sorted(missing_symbols):
        body.append(f"void {sym}(void);")
        body.append(f"void {sym}(void) {{ }}")
    src.write_text("\n".join(body) + "\n")
    obj = out_dir / "stubs.o"
    if _run(["cc", "-c", str(src), "-o", str(obj)]).returncode:
        return None
    archive = out_dir / "stubs.a"
    if _run(["ar", "rcs", str(archive), str(obj)]).returncode:
        return None
    return archive


def engine_objects(pack):
    """build/core/**/*.o plus THIS pack's own build/packs/<pack.id>/**/*.o -
    never a glob of all of build/. With two packs' objects present, a glob of
    the whole tree links both packs' suites into one binary, and both define
    a `g_suites[]` - the link-time collision this is written to avoid."""
    objs = sorted((paths.ROOT / "build" / "core").rglob("*.o"))
    objs += sorted((paths.ROOT / "build" / "packs" / pack.id).rglob("*.o"))
    if not objs:
        raise BuildError("engine objects missing - run `make` in the bro42 directory")
    return objs


def _source_candidates(pack, symbol):
    """Basenames in pack.sources that could plausibly define `symbol`: the
    bare name and its `_bonus` variant. Empty when the pack has no closed
    source set (sources is None) - there is nothing to look for on disk."""
    if pack.sources is None:
        return []
    return [n for n in (symbol, f"{symbol}_bonus") if n in pack.sources]


def prepare(target, pack):
    """Returns (binary_path, info). Never raises for a broken student repo."""
    target = Path(target).resolve()
    cache = paths.cache_dir(target, pack)
    info = {"target": str(target), "cache": str(cache)}

    info["make"] = make_target(target)
    archive = find_archive(target, pack)
    if archive is None and pack.sources is not None:
        archive = compile_known_sources(target, pack, cache / "objs", info)
        info["archive_source"] = "compiled from known basenames"
    elif archive is not None:
        info["archive_source"] = "make"
    else:
        info["archive_source"] = None

    if archive is None:
        info["present"] = set()
        detail = ""
        if pack.sources is None:
            detail = (f"\n  {pack.display} has no closed set of source names "
                      f"bro42 is willing to guess at - fix the build so "
                      f"`make` produces {pack.artifact[1]}")
        else:
            errs = info.get("compile_errors") or []
            if errs:
                lines = [l for e in errs for l in e.splitlines()
                         if "error:" in l][:4]
                detail = "\n  " + "\n  ".join(lines) if lines else ""
            elif not list(Path(target).glob("*.c")):
                detail = "\n  the directory contains no .c files"
        info["error"] = (f"no {pack.artifact[1]}, and " +
                         ("nothing to fall back on" if pack.sources is None
                          else "none of the known source files here would compile")
                         + detail)
        return None, info

    present_symbols = defined_symbols(archive)
    missing_suites = pack.missing_suites(present_symbols)
    info["missing"] = missing_suites
    # Roadmap/next-function logic (cli.cmd_next) walks suite ids, not
    # symbols - a suite is "present" exactly when its symbol is defined.
    info["present"] = set(pack.suite_ids) - set(missing_suites)

    missing_symbols = sorted({pack.symbol_of(s) for s in missing_suites})

    # "Missing" covers two very different situations, and telling a student
    # "not written yet" about a file they DID write sends them looking for the
    # wrong problem. A source that exists but whose symbol never reached the
    # archive did not compile.
    not_compiling_symbols = {
        sym for sym in missing_symbols
        if any((target / f"{c}.c").is_file() for c in _source_candidates(pack, sym))
    }
    info["not_compiling"] = [
        s for s in missing_suites if pack.symbol_of(s) in not_compiling_symbols
    ]
    info["not_written"] = [s for s in missing_suites if s not in info["not_compiling"]]

    # A function whose own source is fine but which CALLS something not written
    # yet cannot work, and it is not the student's fault. ft_strlcat calls
    # ft_memchr; without it, linking against a no-op stub produces a handful of
    # red failures in code that is correct, and the real cause - one unwritten
    # function - is nowhere on the screen. Worse, a stub returning NULL where a
    # pointer gets dereferenced can segfault. So these are not run at all.
    gone = set(missing_symbols)
    deps = undefined_pack_symbols(archive, pack)
    blocked_symbols = {}
    changed = True
    while changed:                       # a block propagates up the call chain
        changed = False
        for sym in pack.symbols:
            if sym in gone or sym in blocked_symbols:
                continue
            need = deps.get(sym, set())
            # resolve to ROOT causes: a dependency that is itself only blocked
            # is not the thing to go and write
            roots = set(need & gone)
            for d in need:
                if d in blocked_symbols:
                    roots |= set(blocked_symbols[d])
            if roots:
                blocked_symbols[sym] = sorted(roots)
                changed = True
    info["blocked"] = {
        s: blocked_symbols[pack.symbol_of(s)]
        for s in pack.suite_ids
        if s not in missing_suites and pack.symbol_of(s) in blocked_symbols
    }

    stubs = write_stubs(missing_symbols, cache)
    binary = cache / "bro_micro"
    cmd = ["cc", "-Wall", "-Wextra", "-g3"]
    cmd += [str(o) for o in engine_objects(pack)]
    cmd += [str(archive)]
    if stubs:
        cmd += [str(stubs)]
    cmd += WRAP_FLAGS
    cmd += ["-o", str(binary)]
    r = _run(cmd)
    if r.returncode:
        info["error"] = "link failed:\n" + r.stderr
        return None, info
    shutil.copystat(archive, archive)
    return binary, info
