"""Build the target, audit its symbols, link the engine against it.

Two of the reference implementation's defects live here (see the audit in
design/01_DECISIONS.md):

  #5  its launcher ran `find -maxdepth 3 -name '*.c'` and ar'd everything it
      found, sweeping up the student's own main.c -> duplicate `main`, link
      failure, zero tests, from a repository that compiles perfectly.
  #2  it detected missing functions with weak stubs returning -999, a sentinel
      that collides with real data: ft_atoi("-999") returns -999.

So: only the 43 known basenames are ever compiled, and presence is decided by
nm before anything is linked.
"""

import shutil
import subprocess
from pathlib import Path

from . import paths

# The functions the engine has suites for. Stage B: one per tier T0-T5.
ENGINE_FUNCS = [
    "ft_isalpha", "ft_isdigit", "ft_isalnum", "ft_isascii", "ft_isprint",
    "ft_toupper", "ft_tolower",
    "ft_strlen", "ft_strchr", "ft_strrchr", "ft_strncmp", "ft_memchr",
    "ft_strnstr", "ft_atoi",
    "ft_memcmp", "ft_memmove", "ft_itoa", "ft_split", "ft_putnbr_fd",
    "ft_lstclear",
    "ft_memset", "ft_bzero", "ft_memcpy", "ft_strlcpy", "ft_strlcat",
    "ft_striteri",
    "ft_calloc", "ft_strdup", "ft_substr", "ft_strjoin", "ft_strtrim",
    "ft_strmapi",
    "ft_putchar_fd", "ft_putstr_fd", "ft_putendl_fd",
    "ft_lstnew", "ft_lstadd_front", "ft_lstsize", "ft_lstlast",
    "ft_lstadd_back", "ft_lstdelone", "ft_lstiter", "ft_lstmap",
]

# -Wl,--wrap rewrites every undefined reference to malloc - including the ones
# inside the student's archive - to __wrap_malloc. GNU ld only; Apple's ld64
# has no equivalent, so on a platform without it the flags are dropped and the
# injection cases report SKIP (decision A8).
WRAP_FLAGS = [
    "-Wl,--wrap=malloc", "-Wl,--wrap=free",
    "-Wl,--wrap=calloc", "-Wl,--wrap=realloc",
]

LIBFT_BASENAMES = {
    "ft_isalpha", "ft_isdigit", "ft_isalnum", "ft_isascii", "ft_isprint",
    "ft_strlen", "ft_memset", "ft_bzero", "ft_memcpy", "ft_memmove",
    "ft_strlcpy", "ft_strlcat", "ft_toupper", "ft_tolower", "ft_strchr",
    "ft_strrchr", "ft_strncmp", "ft_memchr", "ft_memcmp", "ft_strnstr",
    "ft_atoi", "ft_calloc", "ft_strdup", "ft_substr", "ft_strjoin",
    "ft_strtrim", "ft_split", "ft_itoa", "ft_strmapi", "ft_striteri",
    "ft_putchar_fd", "ft_putstr_fd", "ft_putendl_fd", "ft_putnbr_fd",
    "ft_lstnew", "ft_lstadd_front", "ft_lstsize", "ft_lstlast",
    "ft_lstadd_back", "ft_lstdelone", "ft_lstclear", "ft_lstiter", "ft_lstmap",
}


class BuildError(Exception):
    pass


def _run(cmd, cwd=None):
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)


def make_target(target):
    """make bonus, falling back to all, then to a bare make. Never fatal."""
    for args in (["make", "bonus"], ["make", "all"], ["make"]):
        r = _run(args, cwd=target)
        if r.returncode == 0:
            return {"ok": True, "cmd": " ".join(args), "output": r.stdout + r.stderr}
    return {"ok": False, "cmd": "make", "output": r.stdout + r.stderr}


def find_archive(target):
    a = Path(target) / "libft.a"
    return a if a.is_file() else None


def synth_header(out_dir):
    """A stand-in libft.h, built from the prototypes in SPEC_MICRO.md.

    A repository can have perfectly good ft_*.c files and no header - the
    student has not written it yet, or it lives somewhere else. Refusing to
    test anything in that case is the wrong answer: the prototypes are already
    the canonical ones, so supply them and run the tests. The missing header
    is still reported as the Subject IV violation it is, by the macro suite.
    """
    from . import content
    protos = [m["prototype"] for m in content.load()["functions"].values()
              if m.get("prototype")]
    path = out_dir / "libft.h"
    path.write_text(
        "/* generated by ft_bro: this repository has no libft.h of its own */\n"
        "#ifndef LIBFT_H\n# define LIBFT_H\n\n"
        "# include <stddef.h>\n# include <stdlib.h>\n# include <unistd.h>\n\n"
        "# ifndef T_LIST_DEFINED\n#  define T_LIST_DEFINED\n"
        "typedef struct s_list\n{\n\tvoid\t\t\t*content;\n"
        "\tstruct s_list\t*next;\n}\tt_list;\n# endif\n\n"
        + "\n".join(protos) + "\n\n#endif\n")
    return path


def compile_known_sources(target, out_dir, info=None):
    """Fallback when make produced no archive. ONLY the 43 known basenames."""
    out_dir.mkdir(parents=True, exist_ok=True)
    includes = [f"-I{target}"]
    if not (Path(target) / "libft.h").is_file():
        synth_header(out_dir)
        includes.append(f"-I{out_dir}")
        if info is not None:
            info["synth_header"] = True
    objs, errors = [], []
    for src in sorted(Path(target).glob("*.c")):
        stem = src.stem
        if stem not in LIBFT_BASENAMES and not stem.endswith("_bonus"):
            continue
        if stem.endswith("_bonus") and stem[:-6] not in LIBFT_BASENAMES:
            continue
        obj = out_dir / (stem + ".o")
        r = _run(["cc", "-c", str(src), "-o", str(obj)] + includes)
        if r.returncode == 0:
            objs.append(obj)
        else:
            errors.append(r.stderr.strip())
    if info is not None:
        info["compile_errors"] = errors
    if not objs:
        return None
    archive = out_dir / "libft.a"
    if _run(["ar", "rcs", str(archive)] + [str(o) for o in objs]).returncode:
        return None
    return archive


def defined_symbols(archive):
    """The implemented set, decided before anything is linked or called."""
    r = _run(["nm", "-g", "--defined-only", str(archive)])
    syms = set()
    for line in r.stdout.splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[1] in ("T", "t"):
            syms.add(parts[2].lstrip("_"))
    return syms


def undefined_ft_symbols(archive):
    """Per object, which ft_* symbols it calls but does not define."""
    r = _run(["nm", "-u", str(archive)])
    deps, obj = {}, None
    for line in r.stdout.splitlines():
        line = line.strip()
        if line.endswith(".o:"):
            obj = line[:-3].replace("_bonus", "")
            continue
        parts = line.split()
        if len(parts) == 2 and parts[0] == "U" and obj:
            sym = parts[1].lstrip("_").split("@")[0]
            if sym.startswith("ft_"):
                deps.setdefault(obj, set()).add(sym.replace("_bonus", ""))
    return deps


def write_stubs(missing, out_dir):
    """No-op stubs, so the link succeeds. They are never CALLED - their suites
    are skipped and reported MISSING - which is exactly the property the -999
    sentinel design lacked."""
    if not missing:
        return None
    src = out_dir / "stubs.c"
    body = ["/* generated: link-only stubs for functions not yet written */"]
    for fn in sorted(missing):
        body.append(f"void {fn}(void);")
        body.append(f"void {fn}(void) {{ }}")
    src.write_text("\n".join(body) + "\n")
    obj = out_dir / "stubs.o"
    if _run(["cc", "-c", str(src), "-o", str(obj)]).returncode:
        return None
    archive = out_dir / "stubs.a"
    if _run(["ar", "rcs", str(archive), str(obj)]).returncode:
        return None
    return archive


def engine_objects():
    objs = sorted((paths.ROOT / "build").rglob("*.o"))
    if not objs:
        raise BuildError("engine objects missing - run `make` in the ft_bro directory")
    return objs


def prepare(target):
    """Returns (binary_path, info). Never raises for a broken student repo."""
    target = Path(target).resolve()
    cache = paths.cache_dir(target)
    info = {"target": str(target), "cache": str(cache)}

    info["make"] = make_target(target)
    archive = find_archive(target)
    if archive is None:
        archive = compile_known_sources(target, cache / "objs", info)
        info["archive_source"] = "compiled from known ft_*.c basenames"
    else:
        info["archive_source"] = "make"

    if archive is None:
        info["present"] = set()
        detail = ""
        errs = info.get("compile_errors") or []
        if errs:
            lines = [l for e in errs for l in e.splitlines()
                     if "error:" in l][:4]
            detail = "\n  " + "\n  ".join(lines) if lines else ""
        elif not list(Path(target).glob("*.c")):
            detail = "\n  the directory contains no ft_*.c files"
        info["error"] = ("no libft.a, and none of the ft_*.c files here would "
                         "compile" + detail)
        return None, info

    present = defined_symbols(archive)
    info["present"] = present
    missing = [f for f in ENGINE_FUNCS if f not in present]
    info["missing"] = missing

    # "Missing" covers two very different situations, and telling a student
    # "not written yet" about a file they DID write sends them looking for the
    # wrong problem. A source that exists but whose symbol never reached the
    # archive did not compile.
    info["not_compiling"] = [
        f for f in missing
        if (target / f"{f}.c").is_file() or (target / f"{f}_bonus.c").is_file()
    ]
    info["not_written"] = [f for f in missing if f not in info["not_compiling"]]

    # A function whose own source is fine but which CALLS something not written
    # yet cannot work, and it is not the student's fault. ft_strlcat calls
    # ft_memchr; without it, linking against a no-op stub produces a handful of
    # red failures in code that is correct, and the real cause - one unwritten
    # function - is nowhere on the screen. Worse, a stub returning NULL where a
    # pointer gets dereferenced can segfault. So these are not run at all.
    gone = set(missing)
    deps = undefined_ft_symbols(archive)
    blocked = {}
    changed = True
    while changed:                       # a block propagates up the call chain
        changed = False
        for fn in ENGINE_FUNCS:
            if fn in gone or fn in blocked:
                continue
            need = deps.get(fn, set())
            # resolve to ROOT causes: a dependency that is itself only blocked
            # is not the thing to go and write
            roots = set(need & gone)
            for d in need:
                if d in blocked:
                    roots |= set(blocked[d])
            if roots:
                blocked[fn] = sorted(roots)
                changed = True
    info["blocked"] = blocked

    stubs = write_stubs(missing, cache)
    binary = cache / "bro_micro"
    cmd = ["cc", "-Wall", "-Wextra", "-g3"]
    cmd += [str(o) for o in engine_objects()]
    cmd += [str(archive)]
    if stubs:
        cmd += [str(stubs)]
    cmd += WRAP_FLAGS
    cmd += ["-o", str(binary)]
    r = _run(cmd)
    if r.returncode:
        info["error"] = "link failed:\n" + r.stderr
        return None, info
    shutil.copystat(archive, archive)
    return binary, info
