#!/usr/bin/env python3
"""Regenerate _dev/plan/rank00/libft-03-inventory.md from the case data.

The inventory is a VIEW. cases.json and roadmap.json are the facts, and they
are themselves generated from the authored specs. Writing it by hand is how
the part names drifted the first time - subject 19.3 moved the list functions
into the mandatory part and the hand-written table still called them bonus.

Not wired into `make`: it writes into _dev, which is private and absent from a
clone. Run it after the case data changes.

    python3 tools/gen_inventory.py
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "_dev" / "plan" / "rank00" / "libft-03-inventory.md"

TIER = {
    0: "T0 reads, returns a scalar or a pointer into an input",
    1: "T1 writes into a caller-owned buffer",
    2: "T2 allocates and returns heap",
    3: "T3 allocates a structure of allocations",
    4: "T4 side effects only, no return value",
    5: "T5 mutates a caller-owned linked structure",
}

# Subject 19.3: IV.2 Part 1, IV.3 Part 2, IV.4 Part 3 - linked list. All three
# are inside Chapter IV, the mandatory part.
PART_NAME = {1: "1 — libc", 2: "2 — additional", 3: "3 — linked list"}

HEADER = """# libft · 03 · Inventory

The 43 functions as data: part, level, engine tier, the subject's prototype, and the external
symbols each part may legally call.

This is what a future project pack copies the shape of. It was scattered across `ft_bro/libft.py`,
the build-check spec and every function header in `libft-01-cases.md`; collected here so one file
answers "what is in this project".

**Generated by `tools/gen_inventory.py`** from `ft_bro/data/cases.json` and `roadmap.json` — which
are themselves generated from `libft-01-cases.md` and `libft-02-learning.md`. Do not edit by hand;
if this disagrees with them, they win.

**On the tier column:** `../platform/04-testdesign.md` carries the same assignments in a
hand-maintained table, and that duplication is deliberate. `make selftest`'s tier-agreement check
compares that hand-written table against `cases.json`; if it compared *this* file instead it would
be comparing `cases.json` with itself and would pass no matter what was wrong. The hand-written
table is the independent declaration. This one is a convenience view.

---

## The permission boundary

Part is not a difficulty ordering. It is what the subject permits each function to call:

| Part | May call | Source |
|---|---|---|
| 1 — libc | `malloc`, `free` (only `ft_calloc`, `ft_strdup`) | Subject IV.2 |
| 2 — additional | `malloc`, `free`, `write` | Subject IV.3 |
| 3 — linked list | `malloc`, `free` | Subject IV.4 |

Calls between your own `ft_*` functions are legal in every part and are not violations — a check
that flags `ft_strjoin` for calling `ft_strlen` is accusing correct code.

**All three parts are mandatory.** Subject 19.3 places Part 3 in Chapter IV alongside the others;
Libft has no bonus part. Repositories started under an older subject keep the list functions in
`ft_lst*_bonus.c` behind a `bonus` rule, which the build and macro checks both accept.

## Engine tiers

What machinery a function's tests require. Cumulative: T3 needs everything T2 needs. Developer-
facing only — a student never sees a tier.

"""


def main():
    cases = json.loads((ROOT / "ft_bro/data/cases.json").read_text())
    roadmap = json.loads((ROOT / "ft_bro/data/roadmap.json").read_text())
    fns, order = cases["functions"], lambda f: cases["functions"][f]["order"]

    counts = {}
    for c in cases["cases"].values():
        counts[c["fn"]] = counts.get(c["fn"], 0) + 1

    out = [HEADER]
    for t in sorted(TIER):
        n = sum(1 for m in fns.values() if m["tier"] == t)
        out.append(f"- **{TIER[t]}** — {n}\n")

    out.append("\n---\n\n## The functions\n\n")
    out.append("| # | Function | Part | Lv | Tier | Cases | Prototype |\n"
               "|---|---|---|---|---|---|---|\n")
    for f in sorted(fns, key=order):
        m = fns[f]
        out.append(f"| {m['order']} | `{f}` | {PART_NAME[m['part']]} | {m['level']} | "
                   f"T{m['tier']} | {counts.get(f, 0)} | `{m.get('prototype', '')}` |\n")
    out.append(f"\n**{len(fns)} functions · {sum(counts.values())} authored cases, "
               f"all mandatory.**\n")

    out.append("\n## Prerequisites\n\nFrom the progressive track in `libft-02-learning.md`. "
               "`bro next` walks this to pick what to\nwrite. A chain head has none.\n\n"
               "| Function | Needs first |\n|---|---|\n")
    for f in sorted(roadmap["functions"], key=lambda x: order(x) if x in fns else 99):
        pre = roadmap["functions"][f].get("prereqs") or []
        if pre:
            out.append(f"| `{f}` | {', '.join('`%s`' % p for p in pre)} |\n")

    if not OUT.parent.is_dir():
        print(f"no {OUT.parent} - nothing to write (this is a clone)", file=sys.stderr)
        return 0
    OUT.write_text("".join(out))
    print(f"functions {len(fns)}   cases {sum(counts.values())}")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
